# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Shenyong Ye
# Description of the Site
description: what's out there
# URL of Image of the Site
site-image: /assets/images/me.png
# Keywords of the Site
site-keywords: Shenyong Ye, PKU, MIT, shenyong0714
# URL for the Image of custom Favicon
favicon-url: /assets/images/icon.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://shenyong0714.github.io/assets/images/meili.JPG

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: shenyongye0714@gmail.com
facebook_username: Shenyong Ye
twitter_username: ShenyongYe07
instagram_username: a.ethan2001
linkedin_username: /
github_username:  shenyong0714
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Shenyong
# URL for the Image of the Author
author-image: /assets/images/me.png
# 60 Words About the Author
author-about:  About me
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/shenyong0714

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
